/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.fatec.view;

/**
 *
 * @author Felipe
 */
public class menuView extends javax.swing.JFrame {

    /**
     * Creates new form menuView
     */
    public menuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        manutencaoMenu = new javax.swing.JMenu();
        novaManutencao = new javax.swing.JMenuItem();
        editaManutencao = new javax.swing.JMenuItem();
        consultaManutencao = new javax.swing.JMenuItem();
        cotacaoMenu = new javax.swing.JMenu();
        novoCotacao = new javax.swing.JMenuItem();
        editaCotacao = new javax.swing.JMenuItem();
        consultaCotacao = new javax.swing.JMenuItem();
        veiculoMenu = new javax.swing.JMenu();
        novoVeiculo = new javax.swing.JMenuItem();
        editaVeiculo = new javax.swing.JMenuItem();
        consultaVeiculo = new javax.swing.JMenuItem();
        motoristaMenu = new javax.swing.JMenu();
        novoMotorista = new javax.swing.JMenuItem();
        editaMotorista = new javax.swing.JMenuItem();
        consultaMotorista = new javax.swing.JMenuItem();
        mecanicoMenu = new javax.swing.JMenu();
        novoMecanico = new javax.swing.JMenuItem();
        editaMecanico = new javax.swing.JMenuItem();
        consultaMecanico = new javax.swing.JMenuItem();
        pecaosMenu = new javax.swing.JMenu();
        novoPecas = new javax.swing.JMenuItem();
        editaPecas = new javax.swing.JMenuItem();
        consultaPecas = new javax.swing.JMenuItem();
        fornecedorMenu = new javax.swing.JMenu();
        fornecedorSubMenu = new javax.swing.JMenuItem();
        usuariooMenu = new javax.swing.JMenu();
        telaInicio = new javax.swing.JMenuItem();
        editarUsuario = new javax.swing.JMenuItem();
        sairSessao = new javax.swing.JMenuItem();

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mitur Control");

        manutencaoMenu.setMnemonic('h');
        manutencaoMenu.setText("Manutenção");
        manutencaoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manutencaoMenuActionPerformed(evt);
            }
        });

        novaManutencao.setMnemonic('a');
        novaManutencao.setLabel("Novo");
        novaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaManutencaoActionPerformed(evt);
            }
        });
        manutencaoMenu.add(novaManutencao);

        editaManutencao.setMnemonic('c');
        editaManutencao.setLabel("Editar");
        editaManutencao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editaManutencaoActionPerformed(evt);
            }
        });
        manutencaoMenu.add(editaManutencao);

        consultaManutencao.setText("Consultar");
        manutencaoMenu.add(consultaManutencao);

        menuBar.add(manutencaoMenu);

        cotacaoMenu.setText("Cotação");

        novoCotacao.setLabel("Novo");
        novoCotacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoCotacaoActionPerformed(evt);
            }
        });
        cotacaoMenu.add(novoCotacao);

        editaCotacao.setLabel("Editar");
        cotacaoMenu.add(editaCotacao);

        consultaCotacao.setLabel("Consulta");
        cotacaoMenu.add(consultaCotacao);

        menuBar.add(cotacaoMenu);

        veiculoMenu.setLabel("Veículo");

        novoVeiculo.setLabel("Novo");
        veiculoMenu.add(novoVeiculo);

        editaVeiculo.setLabel("Editar");
        veiculoMenu.add(editaVeiculo);

        consultaVeiculo.setLabel("Consulta");
        veiculoMenu.add(consultaVeiculo);

        menuBar.add(veiculoMenu);

        motoristaMenu.setLabel("Motorista");

        novoMotorista.setLabel("Novo");
        motoristaMenu.add(novoMotorista);

        editaMotorista.setLabel("Editar");
        motoristaMenu.add(editaMotorista);

        consultaMotorista.setLabel("Consulta");
        motoristaMenu.add(consultaMotorista);

        menuBar.add(motoristaMenu);

        mecanicoMenu.setLabel("Mêcanico");

        novoMecanico.setLabel("Novo");
        mecanicoMenu.add(novoMecanico);

        editaMecanico.setLabel("Editar");
        mecanicoMenu.add(editaMecanico);

        consultaMecanico.setLabel("Consulta");
        mecanicoMenu.add(consultaMecanico);

        menuBar.add(mecanicoMenu);

        pecaosMenu.setLabel("Peças");

        novoPecas.setLabel("Novo");
        pecaosMenu.add(novoPecas);

        editaPecas.setLabel("Editar");
        pecaosMenu.add(editaPecas);

        consultaPecas.setLabel("Consulta");
        pecaosMenu.add(consultaPecas);

        menuBar.add(pecaosMenu);

        fornecedorMenu.setText("Fornecedor");

        fornecedorSubMenu.setText("Ir para Fornecedor");
        fornecedorSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fornecedorSubMenuActionPerformed(evt);
            }
        });
        fornecedorMenu.add(fornecedorSubMenu);

        menuBar.add(fornecedorMenu);

        usuariooMenu.setText("Usuario");

        telaInicio.setText("Tela de nicio");
        usuariooMenu.add(telaInicio);

        editarUsuario.setLabel("Editar");
        usuariooMenu.add(editarUsuario);

        sairSessao.setText("Sair");
        usuariooMenu.add(sairSessao);

        menuBar.add(usuariooMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editaManutencaoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editaManutencaoActionPerformed

    private void novaManutencaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaManutencaoActionPerformed
        //Ir para a tela de cadastro de manutencao
        menuManutencaoNovoView novoManutencao = new menuManutencaoNovoView();
        this.desktopPane.add(novoManutencao);
        novoManutencao.setVisible(true);
       
    }//GEN-LAST:event_novaManutencaoActionPerformed

    private void manutencaoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manutencaoMenuActionPerformed
        
        
    }//GEN-LAST:event_manutencaoMenuActionPerformed

    private void novoCotacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoCotacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_novoCotacaoActionPerformed

    private void fornecedorSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fornecedorSubMenuActionPerformed

        menuFornecedorView novoFornecedor = new menuFornecedorView();
        this.desktopPane.add(novoFornecedor);
        novoFornecedor.setVisible(true);
    }//GEN-LAST:event_fornecedorSubMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem consultaCotacao;
    private javax.swing.JMenuItem consultaManutencao;
    private javax.swing.JMenuItem consultaMecanico;
    private javax.swing.JMenuItem consultaMotorista;
    private javax.swing.JMenuItem consultaPecas;
    private javax.swing.JMenuItem consultaVeiculo;
    private javax.swing.JMenu cotacaoMenu;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem editaCotacao;
    private javax.swing.JMenuItem editaManutencao;
    private javax.swing.JMenuItem editaMecanico;
    private javax.swing.JMenuItem editaMotorista;
    private javax.swing.JMenuItem editaPecas;
    private javax.swing.JMenuItem editaVeiculo;
    private javax.swing.JMenuItem editarUsuario;
    private javax.swing.JMenu fornecedorMenu;
    private javax.swing.JMenuItem fornecedorSubMenu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu manutencaoMenu;
    private javax.swing.JMenu mecanicoMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu motoristaMenu;
    private javax.swing.JMenuItem novaManutencao;
    private javax.swing.JMenuItem novoCotacao;
    private javax.swing.JMenuItem novoMecanico;
    private javax.swing.JMenuItem novoMotorista;
    private javax.swing.JMenuItem novoPecas;
    private javax.swing.JMenuItem novoVeiculo;
    private javax.swing.JMenu pecaosMenu;
    private javax.swing.JMenuItem sairSessao;
    private javax.swing.JMenuItem telaInicio;
    private javax.swing.JMenu usuariooMenu;
    private javax.swing.JMenu veiculoMenu;
    // End of variables declaration//GEN-END:variables

}
